name: probAI
channels: [pytorch, nvidia, conda-forge]
dependencies:
  - python=3.10
  - pytorch
  - ipykernel
  - torchvision
  - numpy
  - matplotlib
  - pip
  - pip:
      - -e .[dev]   # installs your package EDITABLE during env creation
